### PR TITLE
Add base_path option to include asset methods

### PR DESCRIPTION
**Pull request by jboler**
Ignore previous comments - I got the specs working after looking at the travis config.

### CODE REVIEW

**Comment by jboler** [comment]
After adding:
```
        storeConfigInMeta: false,
        fingerprint: {
          generateAssetMap: true
        }
```
The 2 feature specs fail with:
```
UnrecognizedURLError: /nested
```
and
```
expected to find css "img[src*=\"logo.png\"]" but there were no matches
```

**Comment by jboler** [comment]
Ignore previous comments - I got the specs working after looking at the travis config.

**Comment by jboler** [comment]
@seanpdoyle Is there any chance this could be merged?

**Comment by franzliedke** [comment]
Yes, please! I wish it would do this automatically, but at least this gives me a way to fix the base URL problem. :)

**Comment by seanpdoyle** [comment]
@jboler thanks for opening this pull request -- sorry for the delay!

I'm sorry, but I don't understand the current implementation doesn't work for you -- would you mind explaining how it doesn't support your use case?

cc: @franzliedke

**Comment by franzliedke** [comment]
It's a path relative to the current URL, not the site's base URL.

**Comment by seanpdoyle** [comment]
@franzliedke I understand the new functionality, but I don't understand the use case.

Given the following situations:
- viewing a `"/"` page, with assets served from your server, browsers will resolve `vendor.js` to `/vendor.js`
- viewing a `"/child"` page, with assets served from your server, browsers will resolve `vendor.js` to `/child/vendor.js`
- viewing a `"/child"` page, with assets served from a CDN, [`ember-cli-build.js` configured to prepend the CDN host](http://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls), [and a `<base href="/child">` element](http://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls), browsers will resolve `vendor.js` to `https://cdn.example.com/child/vendor.js`

In what ways do your use cases not fit into one of those scenarios?

**Comment by jboler** [comment]
See my issue: https://github.com/seanpdoyle/ember-cli-rails-assets/issues/6

**Comment by franzliedke** [comment]
Huh? How does that help me when I render the ember_script_tags both on /foo/ and on /foo/bar/?

**Comment by seanpdoyle** [comment]
@jboler thanks for the clarification -- I understand now.

Instead of extending this gem to further monkey with the EmberCLI-generated URLs, would you be able to achieve the same thing [by prepending asset URLs with the absolute path during EmberCLI's asset compilation](http://ember-cli.com/user-guide/#fingerprinting-and-cdn-urls)?

**Comment by seanpdoyle** [comment]
@franzliedke thanks for mentioning that you're rendering script tags on both `/foo/` and `/foo/bar/`.

Could you please elaborate further on how you're trying to use the gam, and the ways in which the current implementation falls short so that I can better understand your problem and possibly offer an alternative solution?

**Comment by jboler** [comment]
@seanpdoyle I can't do that during asset compilation because (as noted in the issue) the `<base>` tag breaks SVG `<def>` paths & `<a>` anchor paths. Basically I think the `<base>` tag is being used incorrectly with ember-cli-rails-assets because it is applied to every URL on the page when there are lots of valid use cases where one doesn't want this to happen.

Also, my Rails app has many different URLs where I need the same Ember app to load so I need `include_ember_script_tags()` to be able produce an absolute URL.

**Comment by seanpdoyle** [comment]
Merged in https://github.com/seanpdoyle/ember-cli-rails-assets/commit/23f9425dda1e4d6c0d50c22de6330743ed4489d2.

Thanks!

**Comment by skylar** [comment]
@seanpdoyle We had poltergeist/capybara-based test that were failing using the `<base>` tag method, and it was holding up our migration to ember-cli 2.3 and your awesome updates on ember-cli-rails. As I was starting to write the same patch, we found and pulled this PR which made the build green.

Looking forward to a new gem version published with this fix. Thanks for supporting this project for the community!

**Comment by seanpdoyle** [comment]
@skylar @jboler this is part of the [`0.6.2` release](https://github.com/seanpdoyle/ember-cli-rails-assets/releases/tag/v0.6.2).

**Comment by skylar** [comment]
@seanpdoyle thanks! :+1:

**Pull request closed without merging**
