### PR TITLE
Release `v0.7.0`

### PR DESCRIPTION
**Pull request by seanpdoyle**

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@tricknotes there's an issue in CI that I'm not sure how to resolve. The last build [is passing](https://github.com/seanpdoyle/ember-cli-rails-assets/commit/39953402b9d0eda92420860b33c961191f5ed5ae), and this commit doesn't make any meaningful changes.

Do you have any ideas on what might be causing the failures, or how to resolve them?

**Comment by tricknotes** [comment]
I'm sorry for my late reply, @seanpdoyle
I wrote a details of failing CI in https://github.com/thoughtbot/ember-cli-rails/pull/599#issuecomment-1425965537.

https://github.com/thoughtbot/ember-cli-rails/pull/599 will fix this PR.

**Comment by tricknotes** [comment]
@seanpdoyle 
Could you release a new version of ember-cli-rails as 0.13.0?
This version will solve dependency issue that fails CI of this PR.

**Comment by seanpdoyle** [comment]
I've updated this code to use the latest ember-cli-rails, and it's still failing.

**Comment by tricknotes** [comment]
https://github.com/seanpdoyle/ember-cli-rails-assets/pull/19 will fix this CI.

**Pull request merged**
